{% set version = "2.0.8" %}

package:
  name: glad2-split
  version: {{ version }}

source:
  url: https://github.com/Dav1dde/glad/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 44f06f9195427c7017f5028d0894f57eb216b0a8f7c4eda7ce883732aeb2d0fc

build:
  number: 0

outputs:
  - name: glad2
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
      entry_points:
        - glad = glad.__main__:main
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - jinja2 >=2.7,<4.0
    test:
      imports:
        - glad
      requires:
        - pip
      commands:
        - pip check

  - name: glad2-cmake
    script: install_cmake.sh  # [unix]
    script: install_cmake.bat  # [win]
    build:
      skip: false
    requirements:
      # dummy build env to avoid EnvironmentLocationNotFound on win
      build:     # [win]
        - cmake  # [win]
      run:
        - {{ pin_subpackage('glad2', exact=True) }}
    test:
      files:
        - CMakeLists.txt
      imports:
        - glad
      requires:
        - cmake
        - ninja
        - pip
      commands:
        - pip check
        - glad --help
        - cmake -G Ninja -B b

    about:
      home: https://github.com/Dav1dde/glad
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: CMake package for glad2.
      description: |
        Example of use:
        ```cmake
        find_package(Glad CONFIG REQUIRED)
        glad_add_library(glad_gl_core_mx_33 REPRODUCIBLE MX API gl:core=3.3)
        ```
        and link `glad_gl_core_mx_33` to target

about:
  home: https://glad.dav1d.de/
  dev_url: https://github.com/Dav1dde/glad
  doc_url: https://github.com/Dav1dde/glad/wiki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Multi-Language Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.
  description: |
    Multi-Language Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.

extra:
  recipe-maintainers:
    - cNoNim
    - traversaro
